# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Testdockeropeyemi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockeropeemi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d7d53a84c23a47dbb652efbc29b60030 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1dbb4ba2b6b94f798c26c5fb15067aac }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockeropeemi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d7d53a84c23a47dbb652efbc29b60030 }}/bulldozer:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Testdockeropeyemi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_98964403d6b54a0897858ac1f6e963b5 }}
        images: 'testdockeropeemi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d7d53a84c23a47dbb652efbc29b60030 }}/bulldozer:${{ github.sha }}'